name: Binance EMA Monitor

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Call EMA Monitor API
        run: |
          curl -X GET "https://dobot.my.id/api/binance-ema?action=run&pairCount=1000"
