name: Binance EMA Monitor
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Call EMA Monitor API
        run: |
          curl --max-time 300 -L -k -H "User-Agent: GitHubActions" -i -X GET "https://dobot.my.id/api/binance-ema?action=run"
